# Generated by Django 4.2.5 on 2023-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
