# Generated by Django 4.2.5 on 2023-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0004_review_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
