# Generated by Django 4.2.5 on 2023-09-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0006_review_user_alter_postimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='full_name',
        ),
    ]
