# Generated by Django 4.2.5 on 2023-09-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primary', '0007_remove_review_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
